# Generated by Django 3.0.5 on 2021-04-15 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=100, verbose_name='유저 이메일')),
                ('user_pw', models.CharField(max_length=100, verbose_name='유저 비밀번호')),
                ('user_created', models.DateTimeField(auto_now_add=True, verbose_name='가입일')),
                ('user_updated', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '사용자',
                'verbose_name_plural': '사용자',
                'db_table': 'members',
            },
        ),
    ]
