# Generated by Django 3.0.5 on 2021-04-20 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_board_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20, verbose_name='차종')),
                ('brand', models.CharField(max_length=20, verbose_name='브랜드')),
                ('design', models.ImageField(height_field=512, upload_to='', verbose_name='디자인', width_field=512)),
            ],
            options={
                'verbose_name': '디자인데이터',
                'verbose_name_plural': '디자인데이터',
                'db_table': 'cars',
            },
        ),
        migrations.AlterField(
            model_name='board',
            name='image',
            field=models.ImageField(blank=True, height_field=512, null=True, upload_to='images/', width_field=512),
        ),
        migrations.CreateModel(
            name='UserCars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_design', models.ImageField(height_field=512, upload_to='', verbose_name='유저 저장 디자인', width_field=512)),
                ('saved_at', models.DateTimeField()),
                ('user_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.Member', verbose_name='유저 이메일')),
            ],
        ),
    ]
