# Generated by Django 3.0.5 on 2021-04-20 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_auto_20210420_1701'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usercars',
            options={'verbose_name': '유저 저장 이미지', 'verbose_name_plural': '유저 저장 이미지'},
        ),
        migrations.AlterField(
            model_name='board',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterModelTable(
            name='usercars',
            table='usercars',
        ),
    ]
